### ISSUE TITLE
请教大佬几个问题

### ISSUE THREAD

**Issue by jeferwang** [taoyu65/UMIAdmin#3]
我对下列问题不太明白,希望大佬不吝赐教

- 我记得这个原先是一个Laravel项目,怎么搞成插件的 

- 还有,如果要是想基于这个扩展进行修改和二次开发,该如何做

> 来自Laravel学习交流群

**Comment by taoyu65** [comment]
这个叫做包开发， 百度或者研究我的代码即可，具体就是在提供者里面定义各种加载路径。
目前项目还在进行中，暂时详细的文档还没有完成，如果你读码能力强的话 应该可以看明白， 我会更新具体二次开发文档。如果哪里需要帮助尽管开口

**Comment by jeferwang** [comment]
多谢啦
